
mysql:
  Host: mysql-course
  Port: 3306
  User: root
  Password: Abc123
  DBName: course
service:
  Version: 1.0.0
  Mode: development
  port: 50051
  Secret: go-courses
  ActiveTokenExpired: 1
  AccessTokenExpiredIn: 24
  RefreshTokenExpiredIn: 720
email:
  AppEmail: management.userxyz@gmail.com
  AppPassword: lkkjakmjuqudztfa
